name: Echidna Core

on:
  push:
    branches:
      - master
      - staged
  pull_request:
    branches:
      - master

jobs:
  IntegrationInvariants:
    strategy:
      matrix:
        testName:
          - PropBalancesEchidnaTest
          - PropReservesEchidnaTest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm run ci-install

      - name: Compile contracts
        run: npm run compile
        working-directory: ./src/core

      - name: Run ${{ matrix.testName }}
        uses: crytic/echidna-action@v2
        with:
          solc-version: 0.8.20
          files: ./src/core/contracts/test/echidna/PoolMockEchidna/${{ matrix.testName }}.sol
          contract: ${{ matrix.testName }}
          crytic-args: --hardhat-ignore-compile
          solc-args: --evm-version paris
          config: ./src/core/contracts/test/echidna/PoolMockEchidna/echidna-property.config.yml

  IntegrationAsserts:
    strategy:
      matrix:
        testName:
          - AssertSwapEchidnaTest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm run ci-install

      - name: Compile contracts
        run: npm run compile
        working-directory: ./src/core

      - name: Run ${{ matrix.testName }}
        uses: crytic/echidna-action@v2
        with:
          solc-version: 0.8.20
          files: ./src/core/contracts/test/echidna/PoolMockEchidna/${{ matrix.testName }}.sol
          contract: ${{ matrix.testName }}
          crytic-args: --hardhat-ignore-compile
          solc-args: --evm-version paris
          config: ./src/core/contracts/test/echidna/PoolMockEchidna/echidna-assert.config.yml

  UnitAsserts:
    strategy:
      matrix:
        testName:
          - BitMathEchidnaTest
          - FullMathEchidnaTest
          - LiquidityMathEchidnaTest
          - LowGasSafeMathEchidnaTest
          - PriceMovementMathEchidnaTest
          - TickMathEchidnaTest
          - TickOverflowSafetyEchidnaTest
          - TickTreeSearchEchidnaTest
          - TickTreeEchidnaTest
          - TokenDeltaMathEchidnaTest
          - UnsafeMathEchidnaTest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm run ci-install

      - name: Compile contracts
        run: npm run compile
        working-directory: ./src/core

      - name: Run ${{ matrix.testName }}
        uses: crytic/echidna-action@v2
        with:
          solc-version: 0.8.20
          files: ./src/core/contracts/test/echidna/${{ matrix.testName }}.sol
          contract: ${{ matrix.testName }}
          crytic-args: --hardhat-ignore-compile
          solc-args: --evm-version paris
          config: ./src/core/contracts/test/echidna/echidna.config.yml
